### ISSUE TITLE
process type fields

### ISSUE THREAD

**Issue by ye0201** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#8]
Hi,
I would like to know "process type" fields in item can be updated by using the cloud app "Item updater by Excel"?

![그림1](https://user-images.githubusercontent.com/126449612/221500474-5a921037-6732-4b59-ab66-8559939ef078.png)

**Comment by ori229** [comment]
I'm afraid not. 
The Cloud App uses Alma's API, and since process_type is only supported for GET (and not for PUT) the Cloud App can not update it as well.

Here is from https://developers.exlibrisgroup.com/wp-content/uploads/alma/xsd/rest_item.xsd :
<xs:element name="process_type" minOccurs="0" maxOccurs="1">
...
<xs:tags>api get</xs:tags>
